{% set version = "1.2.6" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-polychrome
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/Polychrome_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/Polychrome/Polychrome_{{ version }}.tar.gz
  sha256: 2a3d64d5a88a9d89571608e21c186206bd23d7810d6468483045edb5f263c30c

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-colorspace
    - r-scatterplot3d
  run:
    - r-base
    - r-colorspace
    - r-scatterplot3d

test:
  commands:
    - $R -e "library('Polychrome')"           # [not win]
    - "\"%R%\" -e \"library('Polychrome')\""  # [win]

about:
  home: http://oompa.r-forge.r-project.org/
  license: Apache-2.0
  summary: Tools for creating, viewing, and assessing qualitative palettes with many (20-30 or more) colors. See Coombes and colleagues (2019) <doi:10.18637/jss.v090.c01>.
  license_family: APACHE
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: Polychrome
# Title: Qualitative Palettes with Many Colors
# Version: 1.2.3
# Date: 2019-08-01
# Author: Kevin R. Coombes, Guy Brock
# Description: Tools for creating, viewing, and assessing qualitative palettes with many (20-30 or more) colors. See Coombes and colleagues (2019) <doi:10.18637/jss.v090.c01>.
# Maintainer: Kevin R. Coombes <krc@silicovore.com>
# Depends: R (>= 3.0)
# Imports: colorspace, scatterplot3d, methods, graphics, grDevices, stats, utils
# Suggests: RColorBrewer, knitr, rmarkdown
# License: Apache License (== 2.0)
# LazyLoad: yes
# LazyData: no
# URL: http://oompa.r-forge.r-project.org/
# VignetteBuilder: knitr
# NeedsCompilation: no
# Packaged: 2019-08-01 12:08:11 UTC; Kevin
# Repository: CRAN
# Date/Publication: 2019-08-01 12:50:14 UTC
