travis:
  secure:
    BINSTAR_TOKEN: NMjpiyXrNLlZwJM6e7/vsDEGYRSxonTy9DCmxZJKrfcKaAtwtEE1bQxMN5eeDLkBFVdOfOMn0APZ/z5Qr4D84dllVAbxzE9z2ChXSxaz+sjef8msSCz4zWKoVsXrUrAz+1j/+UUjxHWX7t5KwECw/SYba5GGqpL3L5ZrLk9bfWy3u4+3UvLy55lEPSyL87faTv4AWUz9NN/O+/paorlVtA+qM+9ipE9hwRX8vAND7A4NYW/xoYOEZwwE2AOkY/ibBbVx9BjuIRLjojOEUOhu5TvAOj/c5Jw8Dkm/RxLTzL3P1gNIPsaVYvEq/vZU6nx0S9xUhgSxZzvVLFNuyPIp3UsVP4glz+n8URQ4sbagY0wyDhugoE246bAPGl26Fz9auwjMjCdSy0PAM5Gvq9ZcbN2cBkLGNTxNvsXVVOFoTUCquxjlIeIKQkzkgg+0NUcTcZU2QbnqonMSVsfiBfwPZsAVydYDSdDiE0ZiSUe5WIjRgS0jaJLeJM5o3DCCjXgWikQ8H+Y9L9zC3HO7lr5/6f9TpesI5QqM5VCTy1/BUCA2W2TuoSrdRJUHs4b77dlC6V8uPuzw8hao3x9+kCrrHWeWAx2HgiIEy0V05b8t4VO4xsUwJUlKd9poPqDA7nWjk5V13HVCeYV8nT3luesMl0aEyMszdqcD+AtaQ7ISC1E=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
